module.exports = [
  '/posts/nuxtjs-on-aws-lambda',
  '/posts/release-info-aws-icon-searcher',
  '/posts/techbook-fest-4-neko-note',
  '/posts/techbook-fest-4-neko-note-after',
  '/posts/techbook-fest-5-neko-note',
  '/posts/techbook-fest-5-neko-note-after',
  '/posts/component-design-based-on-atomic-design',
  '/posts/release-info-vue-uid',
  '/posts/vuejs-component-with-css-framework',
  '/posts/i-became-a-freelance',
  '/posts/vue-composition-api-columns',
  '/posts/software-engineer-may-breaks-business',
  '/privacy_policy',
  // '/about',
  // '/works',
  // '/slides',
  // '/contact',
]
